a=input('Input Your 1 Number:')
b=input('Input Your 2 Number:')
c=input('Your Your  3 Number :')
d=input('Your Your  4 Number:')
e=input('Your Your  5 Number:')
print("Float of %s Equal "%a,float(a))
print("complex of %s Equal "%a,complex(a))
print("Float of %s Equal "%b,float(b))
print("complex of %s Equal "%b,complex(b))
print("Float of %s Equal "%c,float(c))
print("complex of %s Equal "%c,complex(c)) 
print("Float of %s Equal "%d,float(d))
print("complex of %s Equal "%d,complex(d))
print("Float of %s Equal "%e,float(e))
print("complex of %s Equal "%e,complex(e))
